export const emojiForType = {
  Normal: '🟦',
  Fighting: '🔴',
  Flying: '🪽',
  Poison: '🟣',
  Ground: '🟤',
  Rock: '🪨',
  Bug: '🐛',
  Ghost: '👻',
  Steel: '⚙️',
  Fire: '🔥',
  Water: '💧',
  Grass: '🍃',
  Electric: '⚡️',
  Psychic: '🔮',
  Ice: '❄️',
  Dragon: '🐉',
  Dark: '🖤',
  Fairy: '🧚',
} as const;

export const tailwindColorForPokemonType = {
  Normal: 'bg-blue-500',
  Fighting: 'bg-red-500',
  Flying: 'bg-blue-300',
  Poison: 'bg-purple-500',
  Ground: 'bg-yellow-500',
  Rock: 'bg-gray-500',
  Bug: 'bg-green-500',
  Ghost: 'bg-purple-800',
  Steel: 'bg-gray-300',
  Fire: 'bg-red-500',
  Water: 'bg-blue-500',
  Grass: 'bg-green-500',
  Electric: 'bg-yellow-300',
  Psychic: 'bg-purple-500',
  Ice: 'bg-blue-200',
  Dragon: 'bg-purple-800',
  Dark: 'bg-gray-800',
  Fairy: 'bg-pink-500',
} as const;
